<?php

namespace Database\Seeders;

use App\Models\EntityType;
use Illuminate\Database\Seeder;

class EntityTypeSeeder extends Seeder
{
    public function run(): void
    {
        $entityTypes = [
            [
                'name' => 'LLC',
                'slug' => 'llc',
                'label' => 'LLC',
                'headline' => 'The Ultimate Guide to Limited Liability Companies (LLCs)',
                'sub_headline' => 'Discover how an LLC combines corporate liability protection with partnership-style tax flexibility — the most popular choice for small business owners across all 50 states.',
                'icon' => 'fa-shield-halved',
                'short_description' => 'Limited liability protection with pass-through taxation for small business owners.',
                'intro_content' => 'A Limited Liability Company (LLC) is a hybrid business structure that combines the personal liability protection of a corporation with the tax benefits and operational flexibility of a partnership. LLC owners, called members, are not personally liable for company debts or lawsuits. The LLC is the most popular entity choice for small business owners because it offers robust asset protection without the complex administrative requirements of a corporation.',
                'description' => 'A Limited Liability Company (LLC) combines the liability protection of a corporation with the tax benefits and flexibility of a partnership. LLC owners (called members) are protected from personal liability for business debts and claims. LLCs offer pass-through taxation, meaning profits are reported on personal tax returns.',
                'seo_title' => 'LLC Formation Guide – Requirements, Costs & Compliance',
                'seo_keywords' => 'LLC, limited liability company, LLC formation, LLC requirements, LLC compliance',
                'seo_description' => 'Complete guide to forming an LLC. Learn about formation requirements, costs, annual compliance, and state-specific filing deadlines.',
                'status' => 1,
                'liability_protection' => 'Limited',
                'taxation_type' => 'Pass-through',
                'ownership_structure' => 'Members (unlimited)',
                'best_for_tagline' => 'Small business owners seeking liability protection',
                'formation_cost_range' => '$50 - $500',
                'compliance_level' => 'Low to Medium',
                'complexity_level' => 'Simple',
                'not_recommended_for' => 'Venture capital-funded startups or businesses planning to go public.',
                'tax_deep_dive' => 'LLCs enjoy pass-through taxation by default, meaning business income is reported on the owners\' personal tax returns — avoiding the double taxation that C Corporations face. LLCs can also elect to be taxed as an S Corporation or C Corporation if beneficial. Self-employment taxes apply to LLC earnings for active members.',
                'tax_treatment_summary' => 'Default pass-through taxation with optional S-Corp or C-Corp election. Members pay self-employment taxes on their share of profits.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Separate Legal Entity', 'description' => 'An LLC is a distinct legal entity separate from its owners. It can own property, sign contracts, and conduct business in its own name.', 'icon_class' => 'fa-building-columns'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Member-Managed or Manager-Managed', 'description' => 'LLCs can be managed directly by their members or by appointed managers — giving flexibility in how the business is run day-to-day.', 'icon_class' => 'fa-users-gear'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Operating Agreement Governs', 'description' => 'The operating agreement outlines ownership percentages, profit distribution, voting rights, and procedures for adding or removing members.', 'icon_class' => 'fa-file-signature'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Pass-Through Taxation', 'description' => 'LLC profits and losses flow through to members\' personal tax returns, avoiding corporate-level taxation while maintaining liability protection.', 'icon_class' => 'fa-chart-pie'],
                    ['type' => 'ADVANTAGE', 'title' => 'Personal Asset Protection', 'description' => 'Your personal assets — home, car, bank accounts — are protected from business debts and lawsuits.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Tax Flexibility', 'description' => 'Choose between pass-through, S-Corp, or C-Corp taxation. Maximize deductions and minimize your overall tax burden.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Minimal Paperwork', 'description' => 'Fewer ongoing compliance requirements than corporations. No board meetings, shareholder reports, or complex record-keeping.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'ADVANTAGE', 'title' => 'Ownership Flexibility', 'description' => 'No restrictions on number or type of members. LLCs can have unlimited members, including foreign individuals and other entities.', 'icon_class' => 'fa-user-group'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Self-Employment Taxes', 'description' => 'LLC members must pay self-employment taxes (Social Security and Medicare) on their share of profits, which can be higher than corporate tax rates.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Limited Fundraising Options', 'description' => 'LLCs cannot issue stock, making it harder to raise venture capital or attract equity investors compared to C Corporations.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Varying State Laws', 'description' => 'Each state has its own LLC regulations, fees, and compliance requirements. Operating in multiple states requires foreign qualification.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual Report Filing', 'description' => 'Most states require LLCs to file an annual or biennial report with the Secretary of State, along with a filing fee ranging from $10 to $800.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Registered Agent Maintenance', 'description' => 'LLCs must maintain a registered agent with a physical address in the state of formation to accept legal documents and official correspondence.', 'icon_class' => 'fa-location-dot'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Operating Agreement Updates', 'description' => 'Keep the operating agreement current with changes in membership, ownership percentages, and management structure.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'State Tax Registrations', 'description' => 'Register for state sales tax, employment tax, and other business taxes as required by your state and local jurisdictions.', 'icon_class' => 'fa-file-invoice'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Choose a Business Name', 'description' => 'Select a unique name that complies with your state\'s LLC naming requirements, typically ending with "LLC" or "Limited Liability Company". Check name availability via your state\'s business search portal.'],
                    ['title' => 'Appoint a Registered Agent', 'description' => 'Designate a registered agent with a physical street address in your formation state to accept legal documents on behalf of your LLC.'],
                    ['title' => 'File Articles of Organization', 'description' => 'Submit the Articles of Organization (or Certificate of Formation) to your state\'s filing agency. Include basic information like your LLC name, address, registered agent, and management structure.'],
                    ['title' => 'Draft an Operating Agreement', 'description' => 'Create an operating agreement that defines membership interests, voting rights, profit distribution, and operating procedures. While not always required by law, this document is essential for protecting your LLC structure.'],
                    ['title' => 'Obtain an EIN', 'description' => 'Apply for an Employer Identification Number (EIN) from the IRS — required for hiring employees, opening business bank accounts, and filing business tax returns.'],
                    ['title' => 'Register for State Taxes', 'description' => 'Depending on your business activities, register for state sales tax, employment tax, and other applicable business taxes with your state\'s Department of Revenue.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'Does an LLC protect my personal assets?', 'answer' => 'Yes. The primary benefit of an LLC is personal liability protection. If your LLC is sued or incurs debts, your personal assets — home, car, savings — are generally protected. However, this protection can be compromised if you personally guarantee a loan or engage in fraudulent activity.'],
                    ['question' => 'How is an LLC taxed?', 'answer' => 'By default, LLCs are taxed as pass-through entities — profits and losses flow through to members\' personal tax returns, avoiding corporate-level taxation. LLCs can also elect S-Corp or C-Corp tax status if it provides tax advantages.'],
                    ['question' => 'How much does it cost to form an LLC?', 'answer' => 'State filing fees range from $50 to $500 depending on the state. Additional costs include registered agent services ($100-$300/year), operating agreement templates ($0-$200), and expedited processing fees if needed.'],
                    ['question' => 'Can I form an LLC in a different state?', 'answer' => 'Yes, you can form an LLC in any state, regardless of where you live or operate. Many entrepreneurs choose Delaware or Wyoming for business-friendly laws. However, you\'ll need to register as a foreign LLC in any other state where you conduct business.'],
                    ['question' => 'What is an operating agreement?', 'answer' => 'An operating agreement is a legal document that outlines your LLC\'s ownership structure, management rules, profit distribution, and operating procedures. It\'s legally required in some states and strongly recommended in all states to protect your limited liability status.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                    ['label' => 'C Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Double', 'complexity_level' => 'Complex', 'ownership_structure' => 'Shareholders', 'best_for_tagline' => 'Venture-backed startups'],
                    ['label' => 'S Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Shareholders (max 100)', 'best_for_tagline' => 'Tax-saving small businesses'],
                    ['label' => 'Sole Proprietorship', 'liability_protection' => 'None', 'taxation_type' => 'Personal', 'complexity_level' => 'Minimal', 'ownership_structure' => 'Single owner', 'best_for_tagline' => 'Freelancers & solo entrepreneurs'],
                ]),
            ],
            [
                'name' => 'C Corporation',
                'slug' => 'c-corporation',
                'label' => 'C Corporation',
                'headline' => 'The Complete C Corporation Guide: Structure, Taxation & Formation',
                'sub_headline' => 'Explore the gold standard for venture-backed startups and publicly traded companies — offering the strongest liability protection and unlimited growth potential.',
                'icon' => 'fa-building',
                'short_description' => 'Strongest liability protection with corporate tax structure, ideal for venture capital funding.',
                'intro_content' => 'A C Corporation is a separate legal entity owned by shareholders that offers the strongest personal liability protection of any business structure. It has a formal management structure with a board of directors and officers. C Corps are subject to corporate income tax (double taxation), but offer unlimited growth potential through stock issuance — making them the preferred structure for venture capital funding and IPOs.',
                'description' => 'A C Corporation is a separate legal entity owned by shareholders, offering the strongest personal liability protection. It has a formal structure with a board of directors, officers, and shareholders. C Corps face double taxation but can raise capital through stock sales.',
                'seo_title' => 'C Corporation Formation Guide – Costs, Requirements & Compliance',
                'seo_keywords' => 'C corporation, C-Corp, incorporation, corporate formation, business corporation',
                'seo_description' => 'Complete guide to forming a C Corporation. Learn about incorporation requirements, costs, board structure, and annual compliance.',
                'status' => 1,
                'liability_protection' => 'Full',
                'taxation_type' => 'Double (Corporate + Personal)',
                'ownership_structure' => 'Shareholders (unlimited)',
                'best_for_tagline' => 'Venture capital-funded startups & large enterprises',
                'formation_cost_range' => '$100 - $1,000',
                'compliance_level' => 'High',
                'complexity_level' => 'Complex',
                'not_recommended_for' => 'Solo entrepreneurs or small local businesses with minimal funding needs.',
                'tax_deep_dive' => 'C Corporations face double taxation: the corporation pays tax on its profits at the corporate tax rate (currently 21% federal), and shareholders pay tax again on dividends received. However, C Corps can retain earnings at potentially lower corporate rates and offer deductible benefits like health insurance for employees.',
                'tax_treatment_summary' => 'Corporate income is taxed at the entity level (21% federal). Dividends paid to shareholders are taxed again as personal income. Capital gains treatment available for stock appreciation.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Separate Legal Entity', 'description' => 'A corporation is a distinct legal entity that exists separately from its owners, providing the strongest asset protection available.', 'icon_class' => 'fa-building-columns'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Board of Directors', 'description' => 'Shareholders elect a board of directors who oversee major corporate decisions. Directors appoint officers to manage day-to-day operations.', 'icon_class' => 'fa-users-gear'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Stock Issuance', 'description' => 'Corporations can issue shares of stock to raise capital. This makes them attractive to venture capitalists and angel investors.', 'icon_class' => 'fa-chart-line'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Formal Record-Keeping', 'description' => 'Corporations must maintain detailed records including board meeting minutes, stock certificates, and annual reports to maintain compliance.', 'icon_class' => 'fa-file-lines'],
                    ['type' => 'ADVANTAGE', 'title' => 'Strongest Liability Protection', 'description' => 'Shareholders are not personally liable for corporate debts or lawsuits, even more so than with an LLC.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Unlimited Growth Potential', 'description' => 'Issue unlimited shares of stock, attract venture capital, and eventually go public through an IPO.', 'icon_class' => 'fa-arrow-trend-up'],
                    ['type' => 'ADVANTAGE', 'title' => 'Employee Benefits', 'description' => 'C Corps can deduct the cost of employee benefits including health insurance, retirement plans, and stock options.', 'icon_class' => 'fa-briefcase'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Double Taxation', 'description' => 'Corporate profits are taxed at the entity level, and dividends are taxed again as personal income to shareholders.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Complex Administration', 'description' => 'Requires annual board meetings, shareholder meetings, board resolutions, and extensive record-keeping.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Higher Formation Costs', 'description' => 'Filing fees, legal costs, and ongoing compliance expenses are significantly higher than for LLCs or sole proprietorships.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual Shareholder Meetings', 'description' => 'Must hold annual shareholder meetings and board of directors meetings, with formal minutes recorded and maintained.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Corporate Tax Returns', 'description' => 'Must file annual corporate tax return (IRS Form 1120) and pay corporate income tax on profits.', 'icon_class' => 'fa-file-invoice'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'State Annual Reports', 'description' => 'File annual reports with the Secretary of State, including updated officer/director information and franchise tax payments.', 'icon_class' => 'fa-file-pen'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Choose a Corporate Name', 'description' => 'Select a unique name ending with "Corporation", "Inc.", "Company", or "Limited". Verify availability through your state\'s business name database.'],
                    ['title' => 'Appoint Directors and Officers', 'description' => 'Name initial board of directors and corporate officers (President, Secretary, Treasurer). Directors oversee major decisions; officers manage daily operations.'],
                    ['title' => 'File Articles of Incorporation', 'description' => 'Submit Articles of Incorporation to the state filing agency. Include the corporate name, registered agent information, purpose statement, and share structure.'],
                    ['title' => 'Draft Corporate Bylaws', 'description' => 'Create corporate bylaws outlining the rules for meetings, voting procedures, director powers, and shareholder rights.'],
                    ['title' => 'Issue Stock Certificates', 'description' => 'Issue stock certificates to initial shareholders and maintain a stock ledger tracking ownership percentages and transfer history.'],
                    ['title' => 'Obtain EIN and Business Licenses', 'description' => 'Apply for an EIN from the IRS, register for state taxes, and obtain any required business licenses and permits.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'What is the difference between a C Corp and S Corp?', 'answer' => 'C Corps have double taxation but unlimited shareholders and no ownership restrictions. S Corps have pass-through taxation but limit shareholders to 100 (all must be US citizens or residents). C Corps are better for venture capital funding and IPOs.'],
                    ['question' => 'How much does it cost to incorporate?', 'answer' => 'State filing fees range from $100 to $1,000. Legal fees for corporate documents (bylaws, stock certificates, board minutes) can add $500 to $2,000. Ongoing costs include annual report fees and franchise taxes.'],
                    ['question' => 'Do I need a board of directors?', 'answer' => 'Yes, all corporations must have a board of directors elected by shareholders. The board oversees major corporate decisions and appoints officers. Even single-shareholder corporations need at least one director.'],
                    ['question' => 'Can a C Corp become an S Corp later?', 'answer' => 'Yes, a C Corporation can elect S Corporation status by filing IRS Form 2553. This election must be made by March 15 of the tax year. There are strict eligibility requirements including shareholder limits and stock class restrictions.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'C Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Double', 'complexity_level' => 'Complex', 'ownership_structure' => 'Shareholders', 'best_for_tagline' => 'Venture-backed startups'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                    ['label' => 'S Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Shareholders (max 100)', 'best_for_tagline' => 'Tax-saving small businesses'],
                ]),
            ],
            [
                'name' => 'S Corporation',
                'slug' => 's-corporation',
                'label' => 'S Corporation',
                'headline' => 'The S Corporation Tax Election Guide: Save on Self-Employment Taxes',
                'sub_headline' => 'Learn how S Corporation status can save you thousands in self-employment taxes while maintaining corporate liability protection.',
                'icon' => 'fa-file-invoice-dollar',
                'short_description' => 'Pass-through taxation with self-employment tax savings for established businesses.',
                'intro_content' => 'An S Corporation is not a business entity type — it\'s a tax election that allows a corporation (or LLC) to be taxed as a pass-through entity while avoiding double taxation. S Corps combine the liability protection of a corporation with the tax benefits of a partnership. Shareholders pay taxes on their share of corporate income at individual rates, and the corporation pays no federal income tax.',
                'description' => 'An S Corporation is a special tax election that allows a corporation to pass corporate income, losses, deductions, and credits through to shareholders. Shareholders report income on personal tax returns, avoiding double taxation.',
                'seo_title' => 'S Corporation Guide – Election Requirements & Tax Benefits',
                'seo_keywords' => 'S corporation, S-Corp, S Corp election, Subchapter S, S Corp requirements',
                'seo_description' => 'Complete guide to S Corporations. Learn about eligibility requirements, tax benefits, filing deadlines, and how to elect S Corp status.',
                'status' => 1,
                'liability_protection' => 'Full',
                'taxation_type' => 'Pass-through (S Corp election)',
                'ownership_structure' => 'Shareholders (max 100, US only)',
                'best_for_tagline' => 'Established businesses wanting tax savings',
                'formation_cost_range' => '$100 - $600',
                'compliance_level' => 'Medium',
                'complexity_level' => 'Moderate',
                'not_recommended_for' => 'Businesses with foreign owners, more than 100 shareholders, or multiple classes of stock.',
                'tax_deep_dive' => 'S Corps offer pass-through taxation — corporate income passes through to shareholders\' personal tax returns, avoiding the double taxation of C Corps. The biggest advantage is self-employment tax savings: S Corp shareholders who work as employees pay payroll taxes only on their reasonable salary, not on all corporate profits. Remaining profits can be distributed as dividends without self-employment tax.',
                'tax_treatment_summary' => 'Pass-through taxation with self-employment tax savings. Shareholders must pay themselves a reasonable salary subject to payroll taxes. Remaining profits can be distributed as tax-free dividends.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Tax Election Status', 'description' => 'S Corp is a tax election, not a business structure. Any corporation or LLC can elect S Corp status by filing IRS Form 2553.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Reasonable Salary Requirement', 'description' => 'S Corp shareholder-employees must pay themselves a reasonable salary subject to payroll taxes before taking profit distributions.', 'icon_class' => 'fa-sack-dollar'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Pass-Through Taxation', 'description' => 'Corporate profits and losses flow through to shareholders\' personal tax returns, avoiding the double taxation of C Corporations.', 'icon_class' => 'fa-arrow-trend-up'],
                    ['type' => 'ADVANTAGE', 'title' => 'Self-Employment Tax Savings', 'description' => 'Only your salary is subject to self-employment tax. Remaining profits can be distributed as dividends — saving 15.3% on Medicare and Social Security taxes.', 'icon_class' => 'fa-sack-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Corporate Liability Protection', 'description' => 'Shareholders enjoy the same personal liability protection as C Corporation shareholders.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Pass-Through Taxation', 'description' => 'Avoid double taxation entirely. Corporate income is taxed only once at the shareholder level.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Strict Ownership Limits', 'description' => 'Maximum 100 shareholders, all must be US citizens or residents. No corporate or partnership shareholders allowed.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'One Stock Class Only', 'description' => 'S Corps can only issue one class of stock, limiting flexibility in structuring investor rights and preferences.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'IRS Scrutiny on Salaries', 'description' => 'The IRS closely monitors S Corp salaries. If your salary is too low, the IRS can reclassify distributions as wages with penalties.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'File IRS Form 2553', 'description' => 'To elect S Corp status, file Form 2553 by March 15 of the tax year. Late elections require additional IRS approval.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual S Corp Tax Return', 'description' => 'File IRS Form 1120-S annually, reporting income, deductions, and distributions to shareholders.', 'icon_class' => 'fa-file-invoice'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Payroll Tax Filings', 'description' => 'S Corp shareholder-employees must be on payroll with regular payroll tax filings (Form 941, Form W-2).', 'icon_class' => 'fa-clock'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Form Your Business Entity', 'description' => 'First, form a corporation or LLC through your state\'s filing agency. Obtain your Articles of Incorporation or Articles of Organization before electing S Corp status.'],
                    ['title' => 'Meet Eligibility Requirements', 'description' => 'Ensure your business qualifies: no more than 100 shareholders, all shareholders must be US citizens or residents, only one class of stock, and certain entity types are ineligible.'],
                    ['title' => 'File IRS Form 2553', 'description' => 'Submit IRS Form 2553 (Election by a Small Business Corporation) within the required timeframe. All shareholders must consent to the election by signing the form.'],
                    ['title' => 'Establish Reasonable Salary', 'description' => 'Determine a reasonable salary for shareholder-employees based on industry standards, job duties, and business profitability. Enroll in payroll processing and withholding.'],
                    ['title' => 'Maintain Corporate Formalities', 'description' => 'Hold annual shareholder meetings, maintain board minutes, and file annual reports with the state to preserve S Corp status.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'Is S Corp status right for my business?', 'answer' => 'S Corp status is ideal for profitable businesses where owners want to reduce self-employment taxes. If your business generates significant profit beyond a reasonable owner salary, S Corp election can save thousands annually. It\'s less beneficial for businesses that reinvest all profits or operate at a loss.'],
                    ['question' => 'When should I elect S Corp status?', 'answer' => 'Many businesses wait until they have consistent profits before electing S Corp status. A common threshold is when net income exceeds $60,000-$80,000, where self-employment tax savings outweigh the additional administrative costs.'],
                    ['question' => 'Can an LLC elect S Corp status?', 'answer' => 'Yes! LLCs can elect S Corp taxation by filing Form 2553. This gives LLC owners both the operational flexibility of an LLC and the tax benefits (self-employment tax savings) of an S Corporation.'],
                    ['question' => 'What happens if I miss the S Corp election deadline?', 'answer' => 'If you miss the March 15 deadline, the IRS may still accept a late election if you have reasonable cause. Otherwise, your S Corp election will take effect the following tax year.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'S Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Shareholders (max 100)', 'best_for_tagline' => 'Tax-saving small businesses'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                    ['label' => 'C Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Double', 'complexity_level' => 'Complex', 'ownership_structure' => 'Shareholders', 'best_for_tagline' => 'Venture-backed startups'],
                ]),
            ],
            [
                'name' => 'Nonprofit',
                'slug' => 'nonprofit',
                'label' => 'Nonprofit',
                'headline' => 'Starting a 501(c)(3) Nonprofit: Complete Formation Guide',
                'sub_headline' => 'Turn your charitable mission into a tax-exempt organization with our step-by-step guide to nonprofit formation and 501(c)(3) application.',
                'icon' => 'fa-hand-holding-heart',
                'short_description' => 'Tax-exempt organization for charitable, educational, and religious purposes.',
                'intro_content' => 'A Nonprofit organization is formed to serve a public benefit rather than generate profits for owners. Nonprofits can apply for 501(c)(3) tax-exempt status with the IRS, allowing them to receive tax-deductible donations and avoid paying federal income tax. They must follow strict rules about how funds are used and cannot distribute profits to members, directors, or officers.',
                'description' => 'A Nonprofit organization serves charitable, educational, religious, or scientific purposes. Nonprofits can apply for 501(c)(3) tax-exempt status with the IRS, allowing tax-deductible donations.',
                'seo_title' => 'Nonprofit Formation Guide – 501(c)(3) Requirements & Compliance',
                'seo_keywords' => 'nonprofit, 501c3, tax-exempt, charitable organization, nonprofit formation',
                'seo_description' => 'Complete guide to forming a Nonprofit organization. Learn about 501(c)(3) requirements, state registration, board structure, and ongoing compliance.',
                'status' => 1,
                'liability_protection' => 'Limited (for directors)',
                'taxation_type' => 'Tax-exempt (501c3)',
                'ownership_structure' => 'No owners — board governed',
                'best_for_tagline' => 'Charitable & mission-driven organizations',
                'formation_cost_range' => '$200 - $2,000',
                'compliance_level' => 'High',
                'complexity_level' => 'Complex',
                'not_recommended_for' => 'For-profit businesses or organizations that want to distribute profits to owners.',
                'tax_deep_dive' => '501(c)(3) organizations are exempt from federal income tax on income related to their exempt purpose. Donors can deduct contributions on their personal tax returns. Nonprofits must ensure no private inurement — profits cannot benefit any private individual. Unrelated business income (UBIT) may still be taxable.',
                'tax_treatment_summary' => 'Federal tax exemption on income related to exempt purpose. Donors receive tax deductions for contributions. State tax exemptions vary. Unrelated business income may be taxable.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Mission-Driven Purpose', 'description' => 'Nonprofits must operate exclusively for charitable, educational, religious, scientific, or literary purposes that benefit the public.', 'icon_class' => 'fa-heart'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Board Governance', 'description' => 'Nonprofits are governed by a board of directors who oversee the organization\'s mission, finances, and operations. No single person owns or controls the organization.', 'icon_class' => 'fa-users'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Tax-Exempt Operations', 'description' => 'Qualified nonprofits pay no federal income tax on income related to their exempt purpose and can receive tax-deductible charitable contributions.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Tax-Deductible Donations', 'description' => 'Donors can deduct contributions on their tax returns, making it easier to raise funds from individuals, foundations, and corporations.', 'icon_class' => 'fa-hand-holding-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Federal Tax Exemption', 'description' => 'Qualified nonprofits pay no federal income tax on income generated from their exempt purpose activities.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Grant Eligibility', 'description' => 'Many government grants, foundation funding, and corporate giving programs are only available to 501(c)(3) organizations.', 'icon_class' => 'fa-award'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Complex Application Process', 'description' => 'Applying for 501(c)(3) status requires extensive paperwork, including articles of incorporation, bylaws, and detailed financial projections.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Strict Operating Rules', 'description' => 'No political campaigning, limited lobbying (under 10%), and no private inurement — profits cannot benefit any individual.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'High Compliance Burden', 'description' => 'Annual IRS Form 990 filings, state registrations, and detailed financial record-keeping requirements.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual IRS Form 990', 'description' => 'Must file IRS Form 990, 990-EZ, or 990-N annually to maintain tax-exempt status, disclosing financial information and activities.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'State Charitable Registration', 'description' => 'Register with each state\'s charitable solicitation office before fundraising in that state. Most states require annual renewal.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Board Meeting Minutes', 'description' => 'Maintain detailed minutes of board meetings, documenting major decisions, conflicts of interest, and governance matters.', 'icon_class' => 'fa-file-lines'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Define Your Mission', 'description' => 'Clearly articulate your charitable, educational, religious, or scientific mission. Your mission statement will be central to your articles of incorporation and 501(c)(3) application.'],
                    ['title' => 'Form a Board of Directors', 'description' => 'Recruit at least three unrelated individuals to serve on your board of directors. Board members oversee the organization\'s mission and ensure legal compliance.'],
                    ['title' => 'File Articles of Incorporation', 'description' => 'File nonprofit articles of incorporation with your state. Include specific language required for 501(c)(3) eligibility regarding purpose, asset distribution, and dissolution.'],
                    ['title' => 'Draft Bylaws', 'description' => 'Create comprehensive bylaws addressing board structure, meeting procedures, conflict of interest policies, and governance rules.'],
                    ['title' => 'Apply for 501(c)(3) Status', 'description' => 'Submit IRS Form 1023 (or Form 1023-EZ) with detailed information about your organization\'s purpose, finances, and governance. Processing takes 2-12 months.'],
                    ['title' => 'Register for State Compliance', 'description' => 'Register with your state\'s charitable solicitation office, apply for state tax exemption, and register for any required state business licenses.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'How long does it take to get 501(c)(3) status?', 'answer' => 'IRS processing times vary from 2 months (Form 1023-EZ) to 6-12 months (Form 1023). You can operate as a nonprofit while your application is pending, and contributions may be retroactively deductible once approved.'],
                    ['question' => 'Can a nonprofit make a profit?', 'answer' => 'Yes, nonprofits can generate revenue and have surplus funds. The key distinction is that profits cannot be distributed to individuals (no private inurement). Profits must be reinvested in the organization\'s exempt purpose.'],
                    ['question' => 'Do nonprofit founders get paid?', 'answer' => 'Yes, nonprofit employees, including founders serving as executive directors, can receive reasonable compensation for their work. Salaries must be comparable to what similar organizations pay for similar roles.'],
                    ['question' => 'What is the difference between a nonprofit and a charity?', 'answer' => 'All charities are nonprofits, but not all nonprofits are charities. A charity is a specific type of 501(c)(3) organization that serves charitable purposes. Other nonprofits include social welfare organizations (501(c)(4)), business leagues (501(c)(6)), and social clubs (501(c)(7)).'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'Nonprofit', 'liability_protection' => 'Limited (directors)', 'taxation_type' => 'Tax-exempt', 'complexity_level' => 'Complex', 'ownership_structure' => 'Board governed', 'best_for_tagline' => 'Charitable organizations'],
                    ['label' => 'For-Profit LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                ]),
            ],
            [
                'name' => 'DBA',
                'slug' => 'dba',
                'label' => 'DBA',
                'headline' => 'DBA Registration Guide: Operating Under a Fictitious Business Name',
                'sub_headline' => 'Learn how to register a Doing Business As (DBA) name to operate your business under a brand name different from your legal entity name.',
                'icon' => 'fa-tag',
                'short_description' => 'Register a trade name to operate your business under a different brand identity.',
                'intro_content' => 'A DBA (Doing Business As), also known as a fictitious business name, trade name, or assumed name, allows a business to operate under a name different from its legal registered name. Sole proprietors, partnerships, LLCs, and corporations can all register DBAs. DBAs do not create a separate legal entity or provide liability protection, but they allow businesses to brand themselves effectively.',
                'description' => 'A DBA (Doing Business As) allows a business to operate under a name different from its legal name. It does not provide liability protection but enables branding flexibility.',
                'seo_title' => 'DBA Guide – Fictitious Business Name Requirements by State',
                'seo_keywords' => 'DBA, doing business as, fictitious business name, trade name, assumed name',
                'seo_description' => 'Complete guide to registering a DBA. Learn about fictitious business name requirements, costs, and renewal rules in each state.',
                'status' => 1,
                'liability_protection' => 'None (depends on entity)',
                'taxation_type' => 'Same as underlying entity',
                'ownership_structure' => 'Same as underlying entity',
                'best_for_tagline' => 'Businesses wanting multiple brand identities',
                'formation_cost_range' => '$10 - $100',
                'compliance_level' => 'Minimal',
                'complexity_level' => 'Minimal',
                'not_recommended_for' => 'Businesses seeking liability protection — DBA alone offers none.',
                'tax_deep_dive' => 'A DBA does not change the tax status of your business. If you operate as a sole proprietor, your DBA income is still reported on Schedule C. LLCs and corporations report DBA income through their normal business tax returns. DBAs have no tax filing requirements on their own.',
                'tax_treatment_summary' => 'No separate tax treatment. All income under a DBA is reported through the underlying business entity\'s tax return.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Trade Name Registration', 'description' => 'A DBA registration is simply a public record linking a business name to a legal entity. It does not create a new legal entity.', 'icon_class' => 'fa-tag'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'County or State Filing', 'description' => 'DBAs are typically filed with the county clerk\'s office or Secretary of State, depending on your state\'s requirements.', 'icon_class' => 'fa-building-columns'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Publication Requirement', 'description' => 'Some states require you to publish your DBA registration in a local newspaper for a specified period to notify the public.', 'icon_class' => 'fa-newspaper'],
                    ['type' => 'ADVANTAGE', 'title' => 'Branding Flexibility', 'description' => 'Operate multiple businesses under different brand names without forming separate legal entities for each one.', 'icon_class' => 'fa-star'],
                    ['type' => 'ADVANTAGE', 'title' => 'Low Cost & Simple', 'description' => 'DBA registration typically costs $10 to $100 and requires minimal paperwork compared to forming a new legal entity.', 'icon_class' => 'fa-sack-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Bank Account Setup', 'description' => 'A DBA allows you to open a business bank account and accept payments under your business name instead of your personal name.', 'icon_class' => 'fa-building-columns'],
                    ['type' => 'DISADVANTAGE', 'title' => 'No Liability Protection', 'description' => 'A DBA alone provides no personal liability protection. You need an LLC or corporation structure for asset protection.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Limited Name Protection', 'description' => 'DBA registration does not prevent others from using a similar business name. Only trademarks provide nationwide name protection.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Renewal Requirements', 'description' => 'Most states require DBA renewal every 5 years. Some counties require annual renewal. Late renewals may incur penalties.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Update on Entity Changes', 'description' => 'If your underlying business structure changes (e.g., from sole prop to LLC), you must file a new DBA registration under the new entity.', 'icon_class' => 'fa-file-pen'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Check Name Availability', 'description' => 'Search your county or state\'s business name database to ensure your desired DBA name is not already in use by another business.'],
                    ['title' => 'Complete DBA Application', 'description' => 'Fill out the DBA/fictitious business name application form with your county clerk\'s office or Secretary of State, providing your legal entity information and the desired trade name.'],
                    ['title' => 'Publish Notice (If Required)', 'description' => 'If your state requires publication, arrange for the DBA notice to be published in a qualifying newspaper for the specified duration.'],
                    ['title' => 'Pay Filing Fee', 'description' => 'Pay the applicable filing fee, typically ranging from $10 to $100 depending on your state and county requirements.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'Does a DBA provide liability protection?', 'answer' => 'No. A DBA is simply a name registration. It does not create a separate legal entity and provides no personal liability protection. You need an LLC or corporation for asset protection.'],
                    ['question' => 'Can an LLC have multiple DBAs?', 'answer' => 'Yes. An LLC can register multiple DBAs to operate different brands or business lines under the same legal entity. Each DBA must be registered separately.'],
                    ['question' => 'Do I need a DBA for an online business?', 'answer' => 'If you\'re operating under your legal name (e.g., John Smith), you may not need a DBA. However, if you want to use a business name (e.g., Smith Consulting), you\'ll need to register a DBA in most states.'],
                    ['question' => 'How long does a DBA registration last?', 'answer' => 'DBA registrations typically last 5 years in most states. Some counties require annual renewal. Always check your local requirements and set reminders for renewal deadlines.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'DBA', 'liability_protection' => 'None', 'taxation_type' => 'Entity-based', 'complexity_level' => 'Minimal', 'ownership_structure' => 'Entity-based', 'best_for_tagline' => 'Multiple brand identities'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                ]),
            ],
            [
                'name' => 'Professional LLC',
                'slug' => 'professional-llc',
                'label' => 'PLLC',
                'headline' => 'Professional LLC (PLLC) Guide for Licensed Professionals',
                'sub_headline' => 'Everything doctors, lawyers, accountants, and other licensed professionals need to know about forming a Professional Limited Liability Company.',
                'icon' => 'fa-user-md',
                'short_description' => 'Specialized LLC for licensed professionals with personal liability protection.',
                'intro_content' => 'A Professional LLC (PLLC) is a specialized LLC designed for licensed professionals such as doctors, lawyers, accountants, architects, and engineers. PLLCs provide personal liability protection while allowing professionals to practice their licensed trade. Requirements vary by state and by profession. Some states require PLLCs for certain licensed services.',
                'description' => 'A PLLC is a specialized LLC for licensed professionals. It provides liability protection while allowing professionals to practice their licensed trade.',
                'seo_title' => 'PLLC Guide – Professional LLC Requirements for Licensed Professionals',
                'seo_keywords' => 'PLLC, professional LLC, professional limited liability company, licensed professionals',
                'seo_description' => 'Complete guide to forming a Professional LLC. Learn about PLLC requirements for doctors, lawyers, accountants, and other licensed professionals.',
                'status' => 1,
                'liability_protection' => 'Limited (varies by state)',
                'taxation_type' => 'Pass-through',
                'ownership_structure' => 'Licensed professionals only',
                'best_for_tagline' => 'Doctors, lawyers, accountants & architects',
                'formation_cost_range' => '$50 - $800',
                'compliance_level' => 'Medium',
                'complexity_level' => 'Moderate',
                'not_recommended_for' => 'Non-licensed businesses or professionals who don\'t need state licensing.',
                'tax_deep_dive' => 'PLLCs are taxed identically to standard LLCs — default pass-through taxation with the option to elect S Corp or C Corp status. The key difference is regulatory: PLLCs must comply with state licensing board requirements. Some states impose additional taxes or fees on PLLCs.',
                'tax_treatment_summary' => 'Same tax treatment as standard LLCs with pass-through taxation. Some states may impose additional professional licensing taxes.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Professional Licensing Required', 'description' => 'All PLLC members must hold valid professional licenses in their field. The PLLC is restricted to providing licensed professional services.', 'icon_class' => 'fa-certificate'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'State-Specific Regulations', 'description' => 'Each state has its own PLLC requirements, naming rules, and restrictions. Some states don\'t allow PLLCs or have profession-specific rules.', 'icon_class' => 'fa-building-columns'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Liability Limitations', 'description' => 'PLLCs protect individual professionals from liability for other members\' malpractice but not from their own professional negligence.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Liability Protection', 'description' => 'Protects personal assets from business debts and claims, including malpractice claims against other PLLC members.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Professional Credibility', 'description' => 'Operating as a PLLC signals professionalism and commitment to clients, patients, and regulatory bodies.', 'icon_class' => 'fa-star'],
                    ['type' => 'ADVANTAGE', 'title' => 'Tax Flexibility', 'description' => 'Same pass-through taxation benefits as standard LLCs with optional S Corp election for tax savings.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Personal Malpractice Liability', 'description' => 'PLLCs do not protect against personal malpractice claims. You must maintain individual professional liability insurance.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Limited Ownership', 'description' => 'Only licensed professionals can be members. Ownership cannot be transferred to non-licensed individuals or entities.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'License Verification', 'description' => 'All members must maintain active professional licenses. Changes in license status must be reported to the state and may affect PLLC eligibility.', 'icon_class' => 'fa-certificate'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual Reporting', 'description' => 'File annual reports and pay applicable fees. Some states require additional professional licensing board filings alongside standard business filings.', 'icon_class' => 'fa-calendar-check'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Verify State Requirements', 'description' => 'Check if your state allows PLLCs and whether your specific profession is eligible. Requirements vary significantly by state and licensing board.'],
                    ['title' => 'Obtain Professional Licenses', 'description' => 'Ensure all founding members hold active, unrestricted professional licenses in the state where the PLLC will be formed.'],
                    ['title' => 'File PLLC Formation Documents', 'description' => 'File Professional LLC articles of organization with the Secretary of State. Some states require approval from the relevant licensing board before filing.'],
                    ['title' => 'Create Operating Agreement', 'description' => 'Draft a PLLC operating agreement addressing professional standards, member qualifications, ownership restrictions, and compliance with licensing board rules.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'Can a PLLC protect me from malpractice claims?', 'answer' => 'No. PLLCs protect you from business debts and other members\' malpractice, but you remain personally liable for your own professional malpractice. Maintain adequate professional liability insurance.'],
                    ['question' => 'What professions can form a PLLC?', 'answer' => 'Common PLLC professions include doctors, surgeons, dentists, lawyers, accountants, architects, engineers, psychologists, and chiropractors. Each state determines which professions are eligible.'],
                    ['question' => 'What\'s the difference between a PLLC and an LLC?', 'answer' => 'A PLLC is specifically for licensed professionals. Key differences: PLLC members must hold professional licenses, ownership is restricted to licensed professionals, and PLLCs must comply with licensing board regulations in addition to standard business requirements.'],
                    ['question' => 'Can I convert my PLLC to a standard LLC?', 'answer' => 'Generally no. If your business no longer provides licensed professional services, you can dissolve the PLLC and form a standard LLC. Converting directly between entity types depends on state laws.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'PLLC', 'liability_protection' => 'Limited (varies)', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Licensed professionals', 'best_for_tagline' => 'Licensed professionals'],
                    ['label' => 'Standard LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members (unlimited)', 'best_for_tagline' => 'Small business owners'],
                ]),
            ],
            [
                'name' => 'Limited Partnership',
                'slug' => 'limited-partnership',
                'label' => 'LP',
                'headline' => 'Limited Partnership (LP) Formation Guide: Roles, Risks & Rewards',
                'sub_headline' => 'Understand how Limited Partnerships work — with general partners managing operations and limited partners investing capital with restricted liability.',
                'icon' => 'fa-handshake',
                'short_description' => 'Partnership structure with general and limited partners for investment ventures.',
                'intro_content' => 'A Limited Partnership (LP) consists of at least one general partner who manages the business and is personally liable for debts, and one or more limited partners who contribute capital but have limited liability and cannot participate in management. LPs are commonly used for real estate investments, venture capital funds, film productions, and family investment vehicles.',
                'description' => 'A Limited Partnership (LP) has general partners who manage the business and are personally liable, and limited partners who invest capital with limited liability. Common for real estate and investments.',
                'seo_title' => 'Limited Partnership Guide – Formation, Requirements & Compliance',
                'seo_keywords' => 'limited partnership, LP, partnership formation, general partner, limited partner',
                'seo_description' => 'Complete guide to forming a Limited Partnership. Learn about LP requirements, general vs. limited partner roles, and compliance obligations.',
                'status' => 1,
                'liability_protection' => 'Limited (for limited partners only)',
                'taxation_type' => 'Pass-through',
                'ownership_structure' => 'General + Limited Partners',
                'best_for_tagline' => 'Real estate & investment funds',
                'formation_cost_range' => '$50 - $500',
                'compliance_level' => 'Low',
                'complexity_level' => 'Moderate',
                'not_recommended_for' => 'Active business owners who want management control with liability protection.',
                'tax_deep_dive' => 'LPs are pass-through entities — all income and losses flow through to partners\' personal tax returns. General partners pay self-employment taxes on their share. Limited partners\' share of income is generally not subject to self-employment tax. Partners receive Schedule K-1 forms annually.',
                'tax_treatment_summary' => 'Pass-through taxation. General partners pay self-employment tax. Limited partners\' income is generally not subject to self-employment tax.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'General Partner Role', 'description' => 'The general partner manages day-to-day operations, makes business decisions, and has unlimited personal liability for partnership debts.', 'icon_class' => 'fa-user-gear'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Limited Partner Role', 'description' => 'Limited partners invest capital and share in profits but cannot participate in management. Their liability is limited to their investment amount.', 'icon_class' => 'fa-sack-dollar'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Partnership Agreement', 'description' => 'The partnership agreement defines profit sharing, capital contributions, voting rights, and procedures for adding or removing partners.', 'icon_class' => 'fa-file-signature'],
                    ['type' => 'ADVANTAGE', 'title' => 'Pass-Through Taxation', 'description' => 'LPs avoid double taxation. All income passes through to partners\' personal tax returns.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Investment Structure', 'description' => 'Ideal for investment vehicles. Limited partners can invest without management responsibilities or personal liability.', 'icon_class' => 'fa-hand-holding-dollar'],
                    ['type' => 'ADVANTAGE', 'title' => 'Flexible Profit Sharing', 'description' => 'Partnership agreements can customize profit and loss allocations among general and limited partners.', 'icon_class' => 'fa-chart-pie'],
                    ['type' => 'DISADVANTAGE', 'title' => 'General Partner Liability', 'description' => 'General partners have unlimited personal liability for partnership debts and obligations.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Limited Partner Restrictions', 'description' => 'Limited partners cannot participate in management without losing their limited liability protection — known as the "control rule."', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Partnership Tax Return', 'description' => 'File annual Form 1065 partnership tax return and provide Schedule K-1 to each partner reporting their share of income and deductions.', 'icon_class' => 'fa-file-invoice'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'State Registration', 'description' => 'Register the LP with the Secretary of State and file annual reports. Some states require disclosure of general partner information.', 'icon_class' => 'fa-building-columns'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Choose a Partnership Name', 'description' => 'Select a name that complies with state requirements, typically ending with "Limited Partnership" or "LP". Check availability with the Secretary of State.'],
                    ['title' => 'Identify General and Limited Partners', 'description' => 'Designate at least one general partner (manages operations, unlimited liability) and one or more limited partners (invest capital, limited liability).'],
                    ['title' => 'File Certificate of Limited Partnership', 'description' => 'Submit a Certificate of Limited Partnership with the state, identifying the general partner(s) and providing basic partnership information.'],
                    ['title' => 'Draft Partnership Agreement', 'description' => 'Create a comprehensive partnership agreement addressing capital contributions, profit/loss allocations, management rights, partner withdrawals, and dissolution procedures.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'What is the difference between a general and limited partner?', 'answer' => 'General partners manage the business and have unlimited personal liability. Limited partners invest capital, share profits, but cannot participate in management and have liability limited to their investment.'],
                    ['question' => 'Can a limited partner lose liability protection?', 'answer' => 'Yes — if a limited partner participates in management or control of the business, they risk losing their limited liability protection. This is known as the "control rule." Limited partners should serve only as passive investors.'],
                    ['question' => 'How are Limited Partnerships taxed?', 'answer' => 'LPs are pass-through entities. The partnership files an information return (Form 1065), but all income flows through to partners\' personal tax returns via Schedule K-1. General partners pay self-employment taxes on their share.'],
                    ['question' => 'Can an LLC be a general partner in an LP?', 'answer' => 'Yes. Using an LLC as the general partner is a common strategy to protect against unlimited personal liability. The LLC serves as general partner, providing corporate liability protection for its owners.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'LP', 'liability_protection' => 'Limited partners only', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'General + Limited Partners', 'best_for_tagline' => 'Investment funds'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited (all members)', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                ]),
            ],
            [
                'name' => 'LLP',
                'slug' => 'llp',
                'label' => 'LLP',
                'headline' => 'Limited Liability Partnership (LLP) Guide for Professional Service Firms',
                'sub_headline' => 'Discover how LLPs protect partners from business liabilities while maintaining the flexibility of a partnership structure.',
                'icon' => 'fa-scale-balanced',
                'short_description' => 'Partnership liability protection for professional service firms like law and accounting.',
                'intro_content' => 'A Limited Liability Partnership (LLP) is a partnership where each partner is protected from personal liability for certain partnership obligations, including debts and claims arising from other partners\' malpractice or negligence. LLPs are popular among professional service firms — law firms, accounting firms, architecture firms, and consulting firms. Not all states allow LLPs.',
                'description' => 'An LLP protects partners from personal liability for certain partnership debts and other partners\' actions. Popular among law, accounting, and consulting firms.',
                'seo_title' => 'LLP Guide – Limited Liability Partnership Requirements & Compliance',
                'seo_keywords' => 'LLP, limited liability partnership, LLP formation, LLP requirements',
                'seo_description' => 'Complete guide to forming an LLP. Learn about LLP requirements, partner liability protection, and state-specific rules.',
                'status' => 1,
                'liability_protection' => 'Partial (partner-to-partner)',
                'taxation_type' => 'Pass-through',
                'ownership_structure' => 'Partners',
                'best_for_tagline' => 'Professional service firms',
                'formation_cost_range' => '$50 - $500',
                'compliance_level' => 'Low',
                'complexity_level' => 'Moderate',
                'not_recommended_for' => 'States that don\'t recognize LLPs; non-professional businesses in some states.',
                'tax_deep_dive' => 'LLPs are pass-through entities — all income and losses flow through to partners\' personal tax returns. Each partner reports their share of LLP income on Schedule E and pays self-employment taxes. The LLP files an annual Form 1065 information return.',
                'tax_treatment_summary' => 'Pass-through taxation. Partners pay self-employment taxes on their share of LLP income.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Partner Liability Protection', 'description' => 'Each partner is protected from personal liability for other partners\' professional malpractice or negligence. You are still liable for your own actions.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Partnership Structure', 'description' => 'All partners can participate in management. Unlike LPs, there are no general vs. limited partner distinctions.', 'icon_class' => 'fa-users'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Professional Focus', 'description' => 'LLPs are primarily designed for licensed professionals. Many states restrict LLPs to certain professional services.', 'icon_class' => 'fa-briefcase'],
                    ['type' => 'ADVANTAGE', 'title' => 'Partner Protection', 'description' => 'Protects your personal assets from claims arising from other partners\' actions, misconduct, or malpractice.', 'icon_class' => 'fa-shield-check'],
                    ['type' => 'ADVANTAGE', 'title' => 'Management Flexibility', 'description' => 'All partners can participate in management decisions without losing liability protection — unlike limited partners in an LP.', 'icon_class' => 'fa-user-gear'],
                    ['type' => 'ADVANTAGE', 'title' => 'Pass-Through Taxation', 'description' => 'Avoid double taxation with all income and losses flowing through to partners\' personal tax returns.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Not Available in All States', 'description' => 'Some states don\'t recognize LLPs, and others only allow LLPs for specific licensed professions like law and accounting.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Personal Malpractice Liability', 'description' => 'You remain personally liable for your own professional malpractice or negligence. LLP protection covers only other partners\' actions.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Annual LLP Registration', 'description' => 'Most states require annual LLP registration renewals and fee payments. Some states require proof of professional liability insurance.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Partnership Tax Return', 'description' => 'File Form 1065 annually and provide Schedule K-1 to each partner reporting their distributive share of income, deductions, and credits.', 'icon_class' => 'fa-file-invoice'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Check State Availability', 'description' => 'Verify that your state recognizes LLPs and that your profession qualifies. Some states restrict LLPs to specific licensed professions.'],
                    ['title' => 'Register with the State', 'description' => 'File a registration statement or certificate of limited liability partnership with the Secretary of State. Provide partner information and registered agent details.'],
                    ['title' => 'Draft Partnership Agreement', 'description' => 'Create a detailed partnership agreement addressing capital contributions, profit sharing, management authority, partner admissions and withdrawals, and dispute resolution.'],
                    ['title' => 'Obtain Licenses and Insurance', 'description' => 'Ensure all partners hold required professional licenses. Maintain professional liability insurance as required by your state and profession.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'How is an LLP different from an LLC?', 'answer' => 'LLPs are partnerships with liability protection among partners — ideal for professional service firms. LLCs offer broader liability protection and can be used by any business. LLPs typically have pass-through taxation while LLCs have more tax flexibility.'],
                    ['question' => 'Can I form an LLP in any state?', 'answer' => 'No. Some states don\'t recognize LLPs, while others restrict them to specific professions. California, Nevada, and Oregon, for example, only allow LLPs for accountants, lawyers, and architects.'],
                    ['question' => 'Does an LLP protect against personal malpractice?', 'answer' => 'No. LLP protection covers partnership obligations and other partners\' actions only. You remain personally liable for your own professional malpractice and negligence. Maintain individual professional liability insurance.'],
                    ['question' => 'How are LLPs taxed?', 'answer' => 'LLPs are pass-through entities. The partnership files an annual Form 1065 information return, and each partner reports their share of income on their personal tax returns. Partners pay self-employment taxes on their distributive share.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'LLP', 'liability_protection' => 'Partial (partner-to-partner)', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Partners', 'best_for_tagline' => 'Professional service firms'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited (all members)', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                    ['label' => 'LP', 'liability_protection' => 'Limited partners only', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'General + Limited Partners', 'best_for_tagline' => 'Investment funds'],
                ]),
            ],
            [
                'name' => 'Sole Proprietorship',
                'slug' => 'sole-proprietorship',
                'label' => 'Sole Proprietorship',
                'headline' => 'Sole Proprietorship Guide: The Simplest Way to Start a Business',
                'sub_headline' => 'The simplest and least expensive business structure to start — ideal for freelancers, consultants, and independent contractors testing a business idea.',
                'icon' => 'fa-user-tie',
                'short_description' => 'Simplest business structure with no formal registration or liability protection.',
                'intro_content' => 'A Sole Proprietorship is the simplest business structure — owned and operated by one person with no legal separation between owner and business. There is no formal registration process, no filing fees, and no ongoing compliance requirements at the state level. However, the owner is personally liable for all business debts and obligations. Sole proprietors report business income on their personal tax returns using Schedule C.',
                'description' => 'A Sole Proprietorship is the simplest business structure, owned and operated by one person. There is no legal separation between owner and business, meaning the owner is personally liable for all debts.',
                'seo_title' => 'Sole Proprietorship Guide – Requirements, Taxes & Liability',
                'seo_keywords' => 'sole proprietorship, sole proprietor, business registration, self-employment',
                'seo_description' => 'Complete guide to Sole Proprietorships. Learn about requirements, tax filing, liability considerations, and when to transition to an LLC.',
                'status' => 1,
                'liability_protection' => 'None',
                'taxation_type' => 'Personal (Schedule C)',
                'ownership_structure' => 'Single owner',
                'best_for_tagline' => 'Freelancers, consultants & sole traders',
                'formation_cost_range' => '$0 - $100',
                'compliance_level' => 'Minimal',
                'complexity_level' => 'Minimal',
                'not_recommended_for' => 'Businesses with significant liability risk, employees, or plans for external funding.',
                'tax_deep_dive' => 'Sole proprietors report all business income and expenses on Schedule C attached to their personal Form 1040 tax return. Net profit is subject to self-employment tax (15.3% for Social Security and Medicare). Business losses can offset other personal income. Sole proprietors must make quarterly estimated tax payments.',
                'tax_treatment_summary' => 'Business income reported on Schedule C with personal Form 1040. Subject to self-employment tax on net earnings. Quarterly estimated tax payments required.',
                'features_data' => json_encode([
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Complete Owner Control', 'description' => 'As the sole owner, you have complete control over all business decisions, profits, and operations without needing approval from partners or directors.', 'icon_class' => 'fa-user-gear'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'Simple Tax Reporting', 'description' => 'Business income is reported directly on your personal tax return using Schedule C. No separate business tax return is needed.', 'icon_class' => 'fa-file-invoice-dollar'],
                    ['type' => 'HOW_IT_WORKS', 'title' => 'No Formal Registration', 'description' => 'In most cases, you can start operating as a sole proprietor immediately without filing any state or federal formation documents.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'ADVANTAGE', 'title' => 'Easiest to Start', 'description' => 'No formation paperwork, no filing fees, and no state registration required. Start operating immediately.', 'icon_class' => 'fa-rocket'],
                    ['type' => 'ADVANTAGE', 'title' => 'Complete Control', 'description' => 'You make all decisions, keep all profits, and don\'t need to consult partners, board members, or shareholders.', 'icon_class' => 'fa-hand'],
                    ['type' => 'ADVANTAGE', 'title' => 'Minimal Compliance', 'description' => 'No annual reports, no board meetings, no complex record-keeping. Focus on your business, not paperwork.', 'icon_class' => 'fa-clock'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Unlimited Personal Liability', 'description' => 'Your personal assets — home, car, savings — are at risk from business debts and lawsuits. No liability protection.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Higher Self-Employment Tax', 'description' => 'You pay the full 15.3% self-employment tax on all net business income, with no opportunity for tax savings available to S Corps.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'DISADVANTAGE', 'title' => 'Harder to Raise Capital', 'description' => 'You cannot sell equity or ownership stakes. Business loans depend on your personal credit. Investors generally require an LLC or corporation.', 'icon_class' => 'fa-triangle-exclamation'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Business Licenses', 'description' => 'While no formal business registration is required, you may still need business licenses, permits, or professional certifications depending on your industry and location.', 'icon_class' => 'fa-file-pen'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Quarterly Estimated Taxes', 'description' => 'Sole proprietors must make quarterly estimated tax payments if they expect to owe more than $1,000 in taxes for the year — covering income tax and self-employment tax.', 'icon_class' => 'fa-calendar-check'],
                    ['type' => 'COMPLIANCE_RULE', 'title' => 'Schedule C Filing', 'description' => 'File Schedule C (Profit or Loss from Business) with your annual personal tax return (Form 1040), detailing business income and deductible expenses.', 'icon_class' => 'fa-file-invoice'],
                ]),
                'steps_data' => json_encode([
                    ['title' => 'Start Operating', 'description' => 'Begin conducting business under your legal name. No formal registration is required at the federal or state level to operate as a sole proprietor.'],
                    ['title' => 'Register a DBA (Optional)', 'description' => 'If you want to operate under a business name other than your legal name, register a Doing Business As (DBA) with your county or state.'],
                    ['title' => 'Obtain an EIN (Optional)', 'description' => 'While not required for sole proprietors without employees, an EIN helps separate business and personal finances and is required if you hire employees.'],
                    ['title' => 'Get Business Licenses', 'description' => 'Check with your city, county, and state for required business licenses, permits, or professional certifications needed for your specific business type.'],
                    ['title' => 'Set Up Tax Reporting', 'description' => 'Track all business income and expenses for Schedule C filing. Make quarterly estimated tax payments to the IRS to avoid penalties.'],
                ]),
                'faqs_data' => json_encode([
                    ['question' => 'Do sole proprietors need to register with the state?', 'answer' => 'In most cases, no. Sole proprietors can start operating immediately without state registration. However, you may need specific business licenses or permits depending on your industry, and a DBA if you use a business name.'],
                    ['question' => 'How is a sole proprietorship taxed?', 'answer' => 'Sole proprietors report business income on Schedule C with their Form 1040. Net profits are subject to self-employment tax (15.3%). Business losses can offset other income. Quarterly estimated tax payments are required.'],
                    ['question' => 'When should I switch from sole proprietorship to an LLC?', 'answer' => 'Consider switching when your business has consistent profits, faces liability risks, or when you want to protect personal assets. Common triggers: hiring employees, signing commercial leases, purchasing significant assets, or reaching $50,000+ in annual revenue.'],
                    ['question' => 'Can a sole proprietor have employees?', 'answer' => 'Yes. Sole proprietors can hire employees. You\'ll need an EIN from the IRS, register with your state\'s employment department, and handle payroll taxes, workers\' compensation insurance, and unemployment insurance.'],
                ]),
                'comparison_data' => json_encode([
                    ['label' => 'Sole Proprietorship', 'liability_protection' => 'None', 'taxation_type' => 'Personal (Schedule C)', 'complexity_level' => 'Minimal', 'ownership_structure' => 'Single owner', 'best_for_tagline' => 'Freelancers & solo entrepreneurs'],
                    ['label' => 'LLC', 'liability_protection' => 'Limited', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Simple', 'ownership_structure' => 'Members', 'best_for_tagline' => 'Small business owners'],
                    ['label' => 'S Corporation', 'liability_protection' => 'Full', 'taxation_type' => 'Pass-through', 'complexity_level' => 'Moderate', 'ownership_structure' => 'Shareholders (max 100)', 'best_for_tagline' => 'Tax-saving small businesses'],
                ]),
            ],
        ];

        foreach ($entityTypes as $type) {
            EntityType::updateOrCreate(
                ['slug' => $type['slug']],
                $type
            );
        }
    }
}
